- name: Install containerd
  include_tasks: "{{ansible_os_family}}.yml"

- name: Create /etc/containerd
  file:
    path: /etc/containerd
    state: directory

- name: Create /etc/containerd/config.toml
  register: containerd_config
  shell: containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml
  notify: restart containerd

- name: Enable CRI plugin
  replace:
    path: /etc/containerd/config.toml
    regexp: 'disabled_plugins = \["cri"\]'
    replace: 'disabled_plugins = []'
  register: containerd_config

- name: Set systemd cgroup driver
  replace:
    path: /etc/containerd/config.toml
    regexp: '(\s+)SystemdCgroup = false(\s+)'
    replace: '\1SystemdCgroup = true\2'
  register: containerd_config

- block:

  - name: Add nvidia runtime
    blockinfile:
      path: /etc/containerd/config.toml
      insertbefore: '\[plugins\."io\.containerd\.grpc\.v1\.cri"\.cni\]'
      block: |
          # Add Nvidia runtime
                    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia]
                        privileged_without_host_devices = false
                        runtime_engine = ""
                        runtime_root = ""
                        runtime_type = "io.containerd.runc.v1"
                        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options]
                          BinaryName = "/usr/bin/nvidia-container-runtime"
                          SystemdCgroup = true
 
  - name: Change runtime to nvidia
    replace:
      path: /etc/containerd/config.toml
      regexp: '^(.*)runtime(.*) = "runc"(.*)$'
      replace: '\1runtime\2 = "nvidia"\3'

  when: docker_nvidia_support | bool

- name: restart containerd
  service:
    name: containerd
    state: restarted
  when: containerd_config is changed

- name: start containerd
  service: name=containerd state=started enabled=yes

- name: Install containerd CNI plugins
  include_tasks: install_cni.yml
  when: docker_containerd_install_cni

- name: install nerdctl client
  unarchive:
    src: https://github.com/containerd/nerdctl/releases/download/v{{docker_nerdctl_version}}/nerdctl-{{docker_nerdctl_version}}-linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    include: ['nerdctl']
    creates: /usr/local/bin/nerdctl
  ignore_errors: yes