- name: Install dependencies in Deb systems
  apt: 
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - wget
    update_cache: yes
    cache_valid_time: 3600
    state: present

- name: Install dependencies in Deb systems
  apt: name=gnupg2,iptables
  when: ansible_distribution != "Ubuntu"

- name: Install dependencies in Deb systems
  apt: name=gnupg-agent
  when: ansible_distribution == "Ubuntu"

- name: Add Docker repo key
  apt_key: url="https://download.docker.com/linux/debian/gpg"
  ignore_errors: yes
  register: add_docker_repo

- name: Add Docker repo key (python 2.7.9 or older)
  shell: curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -qq - >/dev/null
  when: add_docker_repo is failed

- name: Add docker-ce  repo
  apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_channel }}'
  when: ansible_distribution == "Ubuntu"

- name: Add docker repo
  apt_repository: repo='deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable' state=present update_cache=yes
  when: ansible_distribution != "Ubuntu"

- name: Install docker latest
  apt: name=docker-ce update_cache=yes
  when: docker_version == "latest"

- name: Install docker {{ docker_version }}
  apt: name="docker-ce={{ docker_version }}" state=present force=yes update_cache=yes
  when: docker_version != "latest"

- name: Install CRIU
  apt: name=criu state=present
  when: docker_install_criu and ansible_distribution_major_version == "16"


- block:

  - name: Download nvidia-docker apt list
    get_url:
      url: https://nvidia.github.io/nvidia-docker/{{ansible_distribution | lower}}{{ansible_distribution_version}}/nvidia-docker.list
      dest: /etc/apt/sources.list.d/nvidia-docker.list
    register: apt_list

  - name: Add nvidia-docker repo key
    apt_key:
      url: "https://nvidia.github.io/nvidia-docker/gpgkey"
      state: present

  - name: Ubuntu apt update
    apt: update_cache=yes
    when: apt_list is changed

  - name: Install nvidia-docker2 package
    apt: name=nvidia-docker2

  - set_fact:
      docker_config_values: "{{ docker_config_values | combine(docker_nvidia_options) }}"

  when: docker_nvidia_support 