- name: Create directory for registry keys
  file:
    path: "/etc/docker/certs.d/{{private_dns_name}}:5000/"
    state: directory

# Create registry certificates
- name: Create the CA private key
  command: openssl genrsa -out ca.key 4096
  args:
    chdir: "/opt/docker_registry/certs"

- name: Create the CA certificate
  command: openssl req -new -x509 -days 365 -key ca.key -out ca.crt  -subj "/C={{country}}/ST={{region}}/L={{city}}/O={{organization}}/OU={{ounit}}/CN={{private_dns_name}}"
  args:
    chdir: "/opt/docker_registry/certs"

- name:  Create a passwordless private key
  command: openssl genrsa -out client.key 4096
  args:
    chdir: "/opt/docker_registry/certs"

- name:  Create a certificate request for the private key
  command: openssl req -nodes -newkey rsa:2048 -keyout {{private_dns_name}}.key -out {{private_dns_name}}.csr -subj "/C={{country}}/ST={{region}}/L={{city}}/O={{organization}}/OU={{ounit}}/CN={{private_dns_name}}"
  args:
    chdir: "/opt/docker_registry/certs"

- name:  Signing the certificates
  command: openssl x509 -req -days 365 -in {{private_dns_name}}.csr -CA ca.crt -CAkey ca.key -set_serial 01 -out {{private_dns_name}}.cert
  args:
    chdir: "/opt/docker_registry/certs"

- name: Copy {{private_dns_name}}.cert file
  copy:
    remote_src: True
    dest: "/etc/docker/certs.d/{{private_dns_name}}:5000/{{private_dns_name}}.cert"
    src: "/opt/docker_registry/certs/{{private_dns_name}}.cert"

- name: Copy {{private_dns_name}}.key file
  copy:
    remote_src: True
    dest: "/etc/docker/certs.d/{{private_dns_name}}:5000/{{private_dns_name}}.key"
    src: "/opt/docker_registry/certs/{{private_dns_name}}.key"

- name: Copy ca.crt file
  copy:
    remote_src: True
    dest: "/etc/docker/certs.d/{{private_dns_name}}:5000/ca.crt"
    src: "/opt/docker_registry/certs/ca.crt"

# Delete unneeded certificates
- name: Create directory for registry keys
  file:
    path: "/opt/docker_registry/certs/{{item}}"
    state: absent
  with_items:
    - "{{private_dns_name}}.csr"
    - client.key"
    - ca.key

- name: Run docker registry
  docker_container:
    name: registry
    image: registry:2
    volumes:
      - /opt/docker_registry:/var/lib/registry
      - /opt/docker_registry/certs:/certs
    ports:
     - "5000:5000"
    env:
        REGISTRY_HTTP_TLS_CERTIFICATE: /certs/mesosserver.cert
        REGISTRY_HTTP_TLS_KEY: /certs/mesosserver.key
    restart_policy: always
