---
# handlers file for docker.ubuntu
- name: reload systemctl
  command: systemctl daemon-reload
  ignore_errors: yes

- name: start docker
  service: name=docker state=started
  when: docker_start_service

- name: reload docker
  service: name=docker state=reloaded

- name: restart docker
  service: name=docker state=restarted
  when: docker_start_service
