---
- name: Converge
  hosts: all
  become: true
  vars: 
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: "Include grycap.docker"
      include_role:
        name: "ansible-role-docker"
